image: node:12

cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  script:
    - npm run build
    # Per https://gitlab.com/gitlab-org/gitlab/-/issues/1719#note_30008931
    - mkdir public
    - mv docs/.vuepress/dist/* public/ 
  artifacts:
    paths:
    - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

