image: node:12

cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  script:
    - npm run build
  artifacts:
    paths:
    - docs/.vuepress/dist
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

